import { chromium, devices } from 'playwright'
const b = await chromium.launch()
const c = await b.newContext({ ...devices['iPhone 13'], locale: 'es-PA' })
const p = await c.newPage()
// Entra como el dueño de la barbería y saca la agenda de verdad.
await p.goto('http://127.0.0.1:3100/entrar', { waitUntil: 'domcontentloaded', timeout: 60000 })
await p.fill('#telefono', '+50760000001')
await p.click('button[type="submit"]')
await p.waitForSelector('#codigo')
const pista = await p.locator('text=Tu código es').textContent()
await p.fill('#codigo', pista.match(/(\d{6})/)[1])
await p.click('button[type="submit"]')
await p.waitForTimeout(3000)
console.log('destino tras entrar:', new URL(p.url()).pathname)
await p.screenshot({ path: 'docs/capturas/bukeo-panel-movil.png', fullPage: true })
console.log('citas en pantalla:', await p.locator('.agenda__fila').count())
await b.close()
